# Generated by Django 4.1.7 on 2023-02-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_topic_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='url_name',
        ),
    ]
