# Generated by Django 4.1.7 on 2023-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_topic_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
