# Generated by Django 4.1.7 on 2023-02-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_topic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='url',
        ),
    ]
